[WIP] VoltageLevel extension
powsybl/powsybl-shortcircuits pull request #11
Opened 2021-08-30 14:29 UTC by colinepiloquet

Signed-off-by: Coline Piloquet <coline.piloquet@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#1

2021-08-31 16:08 UTC, annetill requested changes

2021-08-31 16:08 UTC, annetill commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/VoltageLevelShortCircuit.java
> +        return "voltageLevelShortCircuits";
Can you remove the `s`?

2021-08-31 16:08 UTC, annetill commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/VoltageLevelShortCircuit.java
> +    double getIpMin();
Unit missing.

2021-08-31 16:08 UTC, annetill commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/VoltageLevelShortCircuit.java
> +     * Get maximum allowable peak short-circuit current
Unit missing.

2021-08-31 16:08 UTC, annetill commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/VoltageLevelShortCircuitAdderImpl.java
> +    double ipMin=0;
Zero is not good here. NaN is better. No do forget space between `=`.

2021-09-02 11:32 UTC, annetill commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/VoltageLevelShortCircuit.java
> +    double getIpMin();
I think that in the rest of the code, we use () and not []...

2021-09-06 08:08 UTC, MioRtia reviewed
This is a good PR! Only remark: if ipMin/ipMax are mandatory, a check should be added for both to ensure they are not `NaN`

2021-09-07 08:15 UTC, merged