Add identifiable and generator XML serializer
powsybl/powsybl-shortcircuits pull request #12
Opened 2021-09-13 14:40 UTC by colinepiloquet

Signed-off-by: Coline Piloquet <coline.piloquet@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#1

2021-09-13 14:43 UTC, colinepiloquet commented on shortcircuits-extensions/src/main/resources/xsd/generatorShortCircuit.xsd
> +            <xs:attribute name="stepUpTransformer" use="required" type="xs:double"/>
Because stepUpTransformer is not mandatory in the extension, I do not know if the "use" parameter should not be to something else?

2021-09-15 07:42 UTC, MioRtia commented on shortcircuits-extensions/src/test/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuitTest.java
> +        Network network = EurostagTutorialExample1Factory.create();
I think it is better to put serializer's tests in dedicating classes, indeed

2021-09-15 07:43 UTC, MioRtia requested changes
You can extend AbstractExtensionXmlSerializer (not sure about the class' name but it is something like that) to avoid duplication

2021-09-15 12:03 UTC, colinepiloquet commented on shortcircuits-extensions/src/main/resources/xsd/generatorShortCircuit.xsd
> +            <xs:attribute name="stepUpTransformer" use="required" type="xs:double"/>
@MioRtia, what do you think?

2021-09-15 13:48 UTC, MioRtia commented on shortcircuits-extensions/src/main/resources/xsd/generatorShortCircuit.xsd
> +            <xs:attribute name="stepUpTransformer" use="required" type="xs:double"/>
If it is not mandatory it should indeed be `use="optional"`

2021-09-15 13:52 UTC, MioRtia commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/IdentifiableShortCircuitXmlSerializer.java
> +                "identifiableShortCircuit.xsd", "http://www.itesla_project.eu/schema/iidm/ext/identifiable_short_circuit/1_0",
Since this one is a new extension, you can use powsybl.org domain

2021-09-15 13:52 UTC, MioRtia commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuitXmlSerializer.java
> +        double stepUpTransformerX = XmlUtil.readDoubleAttribute(context.getReader(), "stepUpTransformerX");
If this one is optional use `readOptionalDoubleAttribute`

2021-09-15 13:52 UTC, MioRtia commented on shortcircuits-extensions/src/main/resources/xsd/generatorShortCircuit.xsd
> +            <xs:attribute name="stepUpTransformerX" use="required" type="xs:double"/>
See remark before

2021-09-15 13:52 UTC, MioRtia commented on shortcircuits-extensions/src/test/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuitTest.java
> +public class GeneratorShortCircuitTest  {
I think you added a blank space by mistake

2021-11-05 09:41 UTC, annetill commented
Merged in powsybl-core.

2021-11-05 09:41 UTC, closed without merging