CgmesImport. Import from CGMES generator and busbarSection attributes
powsybl/powsybl-shortcircuits pull request #18
Opened 2021-11-10 10:42 UTC by marqueslanauja

…ections (ipMax).

Signed-off-by: José Antonio Marqués <marquesja@aia.es>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2021-11-29 14:51 UTC, miovd commented on pom.xml
> +        <powsybl-core.version>4.5.0</powsybl-core.version>
You can bump to 4.5.1

2021-11-29 14:51 UTC, miovd commented on shortcircuits-extensions/pom.xml
> +        </dependency>
Shouldn't it be on runtime or test scope? You only need triple-store-api on compile scope

2021-11-29 14:51 UTC, miovd commented on shortcircuits-extensions/pom.xml
> +        </dependency>
Don't forget to specify test scope

2021-11-29 14:51 UTC, miovd commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +    private Network network;
This can be final

2021-11-29 14:51 UTC, miovd commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/CgmesScImporter.java
> +    private CgmesScModel cgmesScModel;
Can be final

2021-11-29 14:51 UTC, miovd commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/CgmesScImporterUtils.java
> +public final class CgmesScImporterUtils {
If all methods are package-private, the class can also be package-private

2021-11-29 14:51 UTC, miovd commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/GeneratorScImporter.java
> +    private Network network;
Can be final

2021-11-29 14:51 UTC, miovd commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/GeneratorScImporter.java
> +class GeneratorScImporter {
Is there a reason it is package-private when all the other classes are public?

2021-12-09 15:12 UTC, marqueslanauja commented on pom.xml
> +        <powsybl-core.version>4.5.0</powsybl-core.version>
Done

2021-12-09 15:13 UTC, marqueslanauja commented on shortcircuits-extensions/pom.xml
> +        </dependency>
Done. Move to test scope.

2021-12-09 15:14 UTC, marqueslanauja commented on shortcircuits-extensions/pom.xml
> +        </dependency>
Done

2021-12-09 15:14 UTC, marqueslanauja commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +    private Network network;
Done

2021-12-09 15:14 UTC, marqueslanauja commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/CgmesScImporter.java
> +    private CgmesScModel cgmesScModel;
Done

2021-12-09 15:14 UTC, marqueslanauja commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/CgmesScImporterUtils.java
> +public final class CgmesScImporterUtils {
Done

2021-12-09 15:15 UTC, marqueslanauja commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/GeneratorScImporter.java
> +    private Network network;
Done

2021-12-09 15:18 UTC, marqueslanauja commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/GeneratorScImporter.java
> +class GeneratorScImporter {
I reviewed all the classes and I changed to package-private all the classes that not need to be public.

2021-12-10 07:33 UTC, annetill commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +class BusbarSectionScImporter {
`Sc` choice is maybe not the good one. As we are not limited in the number of characters, I think that it is better to write `ShortCircuit`, no ?

2021-12-10 07:37 UTC, annetill commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +                    .withIpMin(0.0)
`0.0` here is not a good choice. We have two options:
- We can change the IIDM extension to make the attribute `IpMin` optional ;
- Or authorize to put something like `NaN` if not defined (as we have in CGMES). 
@miovd and @colinepiloquet what is the best option ?

2021-12-10 07:38 UTC, annetill commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +                .withIpMin(0.0)
Same comment here.

2021-12-10 07:40 UTC, annetill requested changes
The main comment is that maybe we have to change the extension rather to put `0.0` for `IpMin` value.

2021-12-10 08:22 UTC, miovd commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +                    .withIpMin(0.0)
@annetill If there is no way to make a short-circuit simulation without `IpMin`, this is the best way... this is the CGMES model that is lacking, this value should be changed in post-processing.
Second option is to do as we do for measurements: add a `valid` parameter and when `valid` is `false`, we can lack some necessary parameters.

2021-12-10 08:29 UTC, annetill commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +                    .withIpMin(0.0)
This is totally related to our own simulator indeed, but I am not sure that it is normal to require `IpMin`.

2021-12-10 08:41 UTC, miovd commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +                    .withIpMin(0.0)
Okay, this should be clarified before making a choice on the extension's design, I think.

2021-12-13 08:45 UTC, annetill commented
> The main comment is that maybe we have to change the extension rather to put `0.0` for `IpMin` value.

https://github.com/powsybl/powsybl-core/pull/1925

2021-12-14 12:05 UTC, marqueslanauja commented on shortcircuits-extensions/src/main/java/com/powsybl/shortcircuits/extensions/importers/cgmes/BusbarSectionScImporter.java
> +class BusbarSectionScImporter {
Done

2021-12-14 12:11 UTC, marqueslanauja commented
> > The main comment is that maybe we have to change the extension rather to put `0.0` for `IpMin` value.
> 
> [powsybl/powsybl-core#1925](https://github.com/powsybl/powsybl-core/pull/1925)

I will wait until version 4.5.2 of powsybl core to remove setting ipMin to 0.0 as this version will include PR #1925.
After removing it, I will move the PR to ready for review.

2021-12-16 10:44 UTC, annetill commented
I am about to bump to powsybl-core 4.6.0-RC1, it means that you can continue this PR after that!

2022-01-21 09:14 UTC, miovd approved these changes

2022-01-21 09:15 UTC, miovd commented
Thank you for your work, it is okay for me! Could you please just fix the conflict?

2022-10-06 10:35 UTC, closed without merging