[WIP] Add Generator extension
powsybl/powsybl-shortcircuits pull request #4
Opened 2021-08-19 13:18 UTC by colinepiloquet

Signed-off-by: Coline Piloquet <coline.piloquet@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#1

2021-08-20 08:46 UTC, MioRtia requested changes

2021-08-20 08:46 UTC, MioRtia commented on iidm-extensions/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Don't forget the copyright

2021-08-20 08:46 UTC, MioRtia commented on iidm-extensions/pom.xml
> +                            <Automatic-Module-Name>com.powsybl.extensions</Automatic-Module-Name>
This should **not** be called `powsybl-iidm-extensions` as another exists in core with the same groupId. use `powsybl-iidm-shortcircuits-extensions`

2021-08-20 08:46 UTC, MioRtia commented on iidm-extensions/pom.xml
> +            <groupId>com.powsybl</groupId>
Valid for all dependencies below: you should use `${project.groupId}` instead of `com.powsybl `. You should also specify the version if it is not in the parent pom.

2021-08-20 08:46 UTC, MioRtia commented on iidm-extensions/pom.xml
> +        </dependency>
Why do you need them? I think you only need `iidm-api` (you might need `iidm-impl` and `config-test` for your tests)

2021-08-20 08:46 UTC, MioRtia commented on iidm-extensions/pom.xml
> +        </dependency>
Why do you need this? On principle: only put what is used. If you're not sure, try deleting it and compiling. If a transitive dependency is necessary, use it and not directly this one.

2021-08-20 08:46 UTC, MioRtia commented on iidm-extensions/src/main/java/com/powsybl/extensions/GeneratorShortCircuit.java
> +    public void setEarthing(boolean earthing);
Valid for below:
- instead of `void` it could return `GeneratorShortCircuit` (this way, one can chain setters)
- `public` does not need to be specified for methods in interfaces

2021-08-20 08:46 UTC, MioRtia commented on iidm-extensions/src/main/java/com/powsybl/extensions/GeneratorShortCircuitImpl.java
> +    private double x2; // Negative sequence reactance
Could you also add these descriptions in the javadoc?

2021-08-20 09:01 UTC, MioRtia commented on iidm-extensions/pom.xml
> +    </properties>
To be deleted: the code is open-source

2021-08-30 15:27 UTC, annetill commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuitAdderImpl.java
> +    double directTransX = -1;
I don't know what is the rule, but `0` or `NaN` is better.

2021-08-31 07:51 UTC, MioRtia requested changes
Could you please resolve the conflicts? (and add your credentials in the parent pom)

2021-08-31 07:51 UTC, MioRtia commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuit.java
> +    Optional<Double> getStepUpTransformerX();
Use `OptionalDouble` directly

2021-08-31 07:51 UTC, MioRtia commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuitImpl.java
> +    private double setUpTransformerX; // Reactance of the step-up transformer
Since this is optional this should be `Double` (that way when it is `null`, the associated method returns an empty optional.

2021-08-31 07:51 UTC, MioRtia commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuitImpl.java
> +        return Optional.ofNullable(setUpTransformerX);
Using `OptionalDouble`, you should do:
```return setUpTransformerX != null ? OptionalDouble.of(setUpTransformerX) : OptionalDouble.empty()``` (Check that `ofNullable` does not exist for `OptionalDouble` in Java 9 but I don't think so)

2021-08-31 10:12 UTC, annetill commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuitAdderImpl.java
> +    double directTransX = Double.NaN;
@MioRtia I think I prefer zero as default values but tell me the usual way to handle that here?

2021-08-31 12:16 UTC, annetill approved these changes

2021-08-31 12:35 UTC, MioRtia commented
I just have a question about why OptionalDouble is used rather than Double.NaN when the value is undefined?

2021-08-31 14:21 UTC, MioRtia commented on iidm-extensions/src/main/java/com/powsybl/shortcircuits/extensions/GeneratorShortCircuitAdderImpl.java
> +        if (Double.isNaN(directTransX)) {
You should add these checks in the `add()` method for the adder :)
After that, this will be good to merge!

2021-08-31 14:39 UTC, MioRtia approved these changes

2021-08-31 14:48 UTC, merged